### ISSUE TITLE
[BUG] Crashes when clicking Main Menu after player death

### ISSUE THREAD

**Issue by bruno-candia** [ImmersiveGames/New-River-Attack#4]
## Description of the Issue
When the player dies in the game and tries to return to the Main Menu, either through the death screen or by clicking the settings option, the game crashes and displays an error message, as demonstrated in the video below.

https://github.com/ImmersiveGames/New-River-Attack/assets/55243348/287b8a8d-62c3-42ca-bf05-19ede490e494

## Steps to Reproduce the Issue
Launch the game.
Play until the character dies.
Click on "Main Menu" (Or open stetting menu and click on "Main Menu")

## Current Behavior
The game crashes and displays an error message after the player dies and attempts to return to the Main Menu.

## Mensagem de Erro
![image](https://github.com/ImmersiveGames/New-River-Attack/assets/55243348/efce6637-3b9e-4620-bc8f-76ed8cbdc0b9)

## Environment
Game Environment: Web Version - Chrome
Operating System: Linux/Ubuntu

**Comment by rinnocenti** [comment]
Uma Correção foi proposta na versão v1.013
